"""Type stubs for ccxt library."""

from typing import Any, Dict, List, Optional, Union

class Exchange:
    """Base exchange class."""

    def __init__(self, config: Optional[Dict[str, Any]] = None) -> None: ...
    def fetch_ticker(self, symbol: str) -> Dict[str, Any]: ...
    def fetch_order_book(self, symbol: str, limit: Optional[int] = None) -> Dict[str, Any]: ...
    def fetch_trades(
        self, symbol: str, since: Optional[int] = None, limit: Optional[int] = None
    ) -> List[Dict[str, Any]]: ...
    def fetch_ohlcv(
        self,
        symbol: str,
        timeframe: str = "1m",
        since: Optional[int] = None,
        limit: Optional[int] = None,
    ) -> List[List[Union[int, float]]]: ...
    def create_market_buy_order(
        self,
        symbol: str,
        amount: float,
        price: Optional[float] = None,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]: ...
    def create_market_sell_order(
        self,
        symbol: str,
        amount: float,
        price: Optional[float] = None,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]: ...
    def create_limit_buy_order(
        self,
        symbol: str,
        amount: float,
        price: float,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]: ...
    def create_limit_sell_order(
        self,
        symbol: str,
        amount: float,
        price: float,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]: ...
    def cancel_order(
        self,
        id: str,
        symbol: Optional[str] = None,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]: ...
    def fetch_order(
        self,
        id: str,
        symbol: Optional[str] = None,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]: ...
    def fetch_orders(
        self,
        symbol: Optional[str] = None,
        since: Optional[int] = None,
        limit: Optional[int] = None,
        params: Optional[Dict[str, Any]] = None,
    ) -> List[Dict[str, Any]]: ...
    def fetch_open_orders(
        self,
        symbol: Optional[str] = None,
        since: Optional[int] = None,
        limit: Optional[int] = None,
        params: Optional[Dict[str, Any]] = None,
    ) -> List[Dict[str, Any]]: ...
    def fetch_closed_orders(
        self,
        symbol: Optional[str] = None,
        since: Optional[int] = None,
        limit: Optional[int] = None,
        params: Optional[Dict[str, Any]] = None,
    ) -> List[Dict[str, Any]]: ...
    def fetch_balance(self, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
    def fetch_trading_fees(self, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
    @property
    def markets(self) -> Dict[str, Dict[str, Any]]: ...
    @property
    def symbols(self) -> List[str]: ...

class kraken(Exchange):
    """Kraken exchange implementation."""

    pass

# Error classes
class BaseError(Exception): ...
class NetworkError(BaseError): ...
class ExchangeError(BaseError): ...
class AuthenticationError(ExchangeError): ...
class PermissionDenied(AuthenticationError): ...
class AccountSuspended(AuthenticationError): ...
class ArgumentsRequired(ExchangeError): ...
class BadRequest(ExchangeError): ...
class BadSymbol(BadRequest): ...
class InsufficientFunds(ExchangeError): ...
class InvalidOrder(ExchangeError): ...
class OrderNotFound(InvalidOrder): ...
class NotSupported(ExchangeError): ...
class ExchangeNotAvailable(NetworkError): ...
class RequestTimeout(NetworkError): ...
class DDoSProtection(NetworkError): ...
class RateLimitExceeded(DDoSProtection): ...
